### ISSUE TITLE
Get tools/nui working with public API -- $100 bounty

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1183]
Right now it's internal API only. It's so much nicer than unlogger when it works!

If you are at the hackathon and solve this, I'll hand you a crisp blueface.

**Comment by littlemountainman** [comment]
Seems like this needs to be done with raw driving data from the comma api. The problem is that the api always returns error 403 "Forbidden. Authenticated user lacks access to desired entity.". I tried other requests with the same JWT token, but this raw driving data request never works. Could it be possible that the user needs to be "superuser" for this ?
