### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by DeeSpeed** [commaai/openpilot#1818]
I have been trying for weeks to get questions answered to no avail.  I have tried Discord (this is a gamers site and I have no idea why this company would use it) and other avenues.  If anyone has suggestions I would appreciate it.  I am sure this is not the proper place to post this but I am very interested in this device.  Thank you.

**Comment by TK211X** [comment]
What vehicle is this for?

What questions do you have?

Are you capable of coding?

Comma decided to switch to Discord because it's free. They expect capable people to join and help themselves if an answer to the question they have exists elsewhere.

![image](https://user-images.githubusercontent.com/33460783/86523580-83657100-be3c-11ea-8b04-da0e8649ac57.png)

**Comment by TK211X** [comment]
See:

https://www.youtube.com/watch?v=jxg1KuowODA
