### ISSUE TITLE
Add check for bad calibration

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#1933]
If a device suddenly moves the calibration will wrong. This is not checked and will cause bad driving behavior.

**Comment by HaraldSchafer** [comment]
It's hard to pick a good strategy for detecting a change in calibration since we don't log that many values. Evaluting the the spread in saved calibration values seems like the best strategy. So let's ship that metric then we can decide thresholds next release

https://github.com/commaai/openpilot/pull/1988

**Comment by HaraldSchafer** [comment]
#2151 makes the calibrator auto reset if a large change is detected. I checked and would have triggered in 6/800 segments. All of which were true positives.
