### ISSUE TITLE
Wifi network crasj

### ISSUE THREAD

**Issue by hooser13** [commaai/openpilot#19527]
Whenever I connect my comma 2 to my home network, all devices lose wifi bandwidth. When 8 disconnect it from the wifi the bandwidth returns to all devices. Do you have a fix?

**Comment by VirtuallyChris** [comment]
I had this happen at my house in Maine before upgrading my internet. It's just due to a device uploading large amounts of data - more than most devices in your house ever would. I bet you'd experience the same thing if you tried uploading a 4k YouTube video on your PC. I'd recommend setting a upload limit in your WiFi router to be below your maximum so it doesn't bog down the network.
