### ISSUE TITLE
Issues Resuming Speed at speed and from stop

### ISSUE THREAD

**Issue by cd85233** [commaai/openpilot#19778]
**Describe the bug**

The following issues are observed related to resuming selected speed:

1. Sometimes hen at a stop (after coming to a stop due to stopped car) OP will not resume.
2. Often When at speed (not from a stop) and the lead car slows down, OP will slow down but will not resume the selected speed. Instead it stays at the last constant speed or slowly decelerates (1mph/5seconds or so)
3. (possibly not related, harder to replicate) When going through and underpass, the car will slow down.

**How to reproduce or log data**

For the issues above, reproduce as follows:
1. Allow lead car to stop while OP is engaged, and the the OP car will stop.
2. Allow the lead car to slow down. 
3. Drive through an underpass

**Expected behavior**

for the issues above:
1-2 The car resumes speed as the lead car speeds up.
3. Speed remains unchanged.

**Device/Version information (please complete the following information):**
 - Device: FrEon
 - Dongle ID: ef51549c7112635e
 - Route: ef51549c7112635e|2021-01-15--16-50-17
 - Timestamp: ~10 minute into drive
 - Version: 0.8.1-release 2
 - Car make/model: 2017 Toyota Highlander XLE (gas not hybrid)

**Additional context**

Code changes from release:
https://github.com/ErichMoraga/openpilot/commit/d72f6be5ff4ba4b377228328d5abf25157005755
https://github.com/ErichMoraga/openpilot/commit/4759891494b3f291e8f94093b98703e70937cc7b

DSU disconnected, no pedal. Black Panda.

**Comment by VirtuallyChris** [comment]
This is an expected issue with using the 'stop and go' hack, which is why we don't ship with it stock. It's not reliable enough to speed up 100% of the time due to the car needing to start rolling before the car starts accepting the acceleration command again. I'd be curious if #2 happens without the 'stop and go' hack as well (if it does you can reopen the issue) If you see 3 happen and can get a log of it, please post a new bug report for it.
