### ISSUE TITLE
Openpilot stopped connecting with 4G

### ISSUE THREAD

**Issue by HumboldtK** [commaai/openpilot#20490]
**Describe the bug**

For the past month my comma device running openpilot has stopped connecting to the internet automatically via SIM card and always shows “connect offline” on the main UI. I noticed this issue at first when I got a notification saying to connect to the internet within two days or openpilot will stop working and I went to the comma app to look back at some footage and there were no recent drives within the last two weeks (but I’ve driven everyday the last two weeks). I am able to connect with WiFi using my phones hotspot. But other than that, it won’t connect anymore automatically, unless it’s connected to a hotspot and I am not able to use the snapshot function on the comma app as it will always show offline as soon as I leave the car. I even tried upgrading to prime as one admin suggested, but that didn’t work. I’ve had the device for about 6 months and this issue only occurred within the last month. I’ve always been able to use the snapshot function and review recent drives without ever connecting it to my hotspot. I haven’t moved or anything so I don’t know why this would be happening. 

**How to reproduce or log data**

Drive. 

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: Eon? Not sure, bought sept 2020. 
 - Dongle ID: acd288bb6090af91
 - Route: all routes. 
 - Timestamp: 
 - Version: 0.8.2
 - Car make/model: Hyundai Sonata 2020

**Additional context**

**Comment by vanillagorillaa** [comment]
So as I understand, you've had the device for six months, but never subscribed to prime, and then one day the SIM no longer has data? If this is the case then I don't see an issue, if you never subscribe to prime then we are paying for a data SIM for your device for you. So we round up a list of devices that have an active SIM and have not subscribed to prime, and then we cancel those lines. It's possible to have a deactivated SIM and still show a 4G connection, you just won't have a data connection. 

I see that your SIM card was activated 12/02/2020 and cancelled 3/10/21. Prime was not activated until yesterday. I'm not sure we currently handle activating prime on a deactivated SIM card. If you don't want prime, or the data subscription that goes with it, or do want prime and the data subscription please email support@comma.ai so that the team can resolve for you.
