### ISSUE TITLE
Updated never runs if thermald crashes on start

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#20522]
If thermald crashes on start `IsOffroad` will never be set causing updated to never run.

**Comment by adeebshihadeh** [comment]
Actually, this isn't the case since updates checks `not params.get("IsOffroad")`, which is equivalent to `not None` in the case where thermald crashes immediately. The case that isn't handled is where thermald runs enough to write the param then crashes. Once updated can safely run onroad, I think we may want to make updated a daemon like athena to be more robust to this kind of stuff.

**Comment by adeebshihadeh** [comment]
updated no longer relies on this param from thermald.
