### ISSUE TITLE
Make clear whether openpilot is controlling longitudinal 

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#20566]
It's not obvious whether your car has stock ACC or OP ACC. It should be easier to see. Perhaps change in the onroad ui, so it is always clear or in the device info in settings?

**Comment by gregjhogan** [comment]
We have a steering icon, maybe add a cruise control icon (standard icon is a speedometer)
https://en.wikipedia.org/wiki/Cruise_control#/media/File:Cruise_Control.svg

**Comment by doktorsleepelss** [comment]
Problem with just an icon is that people could think long isn't working instead of it not being supported.  Would still need something else. For unrelated reasons though, I would love an animated working speedometer icon like the steering wheel. Would be useful to have for replay reasons on explorer. 

Having it in device info would be good though.  Possibly along with other limitations like stop and go support. Problem with that is having people know and check it's there.  Add a settings overview to onboarding?

**Comment by cydia2020** [comment]
Put a "No Longitudinal Control" alert at startup would do imo

**Comment by pd0wm** [comment]
Or we remove the set speed completely if you don't have OP long?

**Comment by dorkmo** [comment]
could put like "honda" under the cruise control logo
