### ISSUE TITLE
Support Kia Sorento 2021 SX

### ISSUE THREAD

**Issue by stondino00** [commaai/openpilot#20641]
Hello,

I have a 2021 Kia Sorento SX Prestige X-Line.  What would be needed from me to help get this car supported?

I don't have any programming knowledge but would like to see this car officially supported like the 2021 Kia Seltos.

I'm new to openpilot and haven't purchased any hardware yet so please be gentle and let me know what I would need to purchase and help with to get this supported.

Thanks

**Comment by adeebshihadeh** [comment]
Closing this since we can't have an issue open for every car we don't support, but feel free to open a discussion on our GitHub Discussions page. Our [discord community](https://discord.comma.ai) can also help you get started. Here's an example of what the car port would look like - https://github.com/commaai/openpilot/pull/20321.
