### ISSUE TITLE
while OP engaged car failed to brake for a lead car

### ISSUE THREAD

**Issue by adnanlanewla** [commaai/openpilot#20830]
**Describe the bug**
Openpilot was engaged in the car. It was following the lead car properly and then all of a sudden, when lead car started braking OP failed to brake for the lead car. The cars AEB and comma's AEB warning system they both went on during this instance and I manually braked.

This bug happened on the route I usually take. I never had any issues in braking when the lead car is in front. So it seems like a pretty serious issue. 

**How to reproduce or log data**
Can't reproduce this bug

**Expected behavior**
OP should have braked while following the lead car

When OP is engaged it should brake for the lead car in front
**Device/Version information (please complete the following information):** 
 - Device: comma2
 - Dongle ID: d2ef5aa690e849d0
 - Route: d2ef5aa690e849d0/2021-05-04--22-50-39/3/fcamera.hevc|d2ef5aa690e849d0/2021-05-04--22-50-39/4/fcamera.hevc
 - Timestamp: (49s-59s)
 - Version: (0.8.3)
 - Car make/model: (2020 Toyota Rav4)

**Additional context**
Here's the youtube video of the stiched segment
https://youtu.be/XdkZxjAmPQ4

**Comment by geohot** [comment]
See https://ibb.co/1RyKr3J for plotjuggler. The lead car braked very hard. There was no issue with detection or controls.

When you disengaged, openpilot was commanding full braking that is allowed by the system. It's level 2, so it's not expected to be able to handle every scenario.

Considering openpilot was at max braking and you got an FCW with plenty of time to handle the situation, I consider this issue closed. While it might be possible to anticipate braking in a holistic manner based on the red light instead of relying on the lead car, this is beyond the scope for now.
