### ISSUE TITLE
Connect to the Internet to check for updates

### ISSUE THREAD

**Issue by rumym** [commaai/openpilot#21323]
Hi, we are currently visiting Canada and I keep getting the below message on my comma ai. I connected to my mobile hotspot and then it lets me drive however, once I restart the car and it is no longer connected to my mobile hotspot it presents the same message again.

dongle id: B4c3c4a8ff4b49f1

Immediately connect to the Internet to check for updates. If you do not connect to the Internet open pilot want to engage in 0 days.

**Comment by adeebshihadeh** [comment]
The updater only runs while the car is off, so you'll need to keep it off and connected to internet until you see the update prompt. We allow the device to go onroad the first time after boot, which is why you it works sometimes for you. The latest release has some updater controls which should help your situation next time.

**Comment by rumym** [comment]
I have connected it while the car is off as well as ACC mode but still nothing happens.

**Comment by adeebshihadeh** [comment]
It's downloading a large update. You can uninstall and reinstall openpilot if you want to watch the progress.

**Comment by rumym** [comment]
Do I need to do this in the car or can I bring the phone unit into the house and do the update while it is disconnected from the car?
