### ISSUE TITLE
Logging/loggerd requirements for training

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#22095]
- [ ] Encoder/Loggerd should keep up with camera streams such that no frames are dropped there, if there are, this should raise a flag
- [ ] All segments should have synchronized camera streams on C3 (i.e. all frames are from the same time)
- [ ] All segments should have same number of frames in 3 camera streams for C3
- [ ] All segments should have 1200 frames
- [ ] If the camera drops a frame, a blank frame should be inserted and a flag raised

Training Data-Quality Checks
- Logging time lags : abs(`roadEncodeIdx/timestampSof` - `controlsState/t`) < 1 sec
- Camera FPS check : Frame diffs of `<camera>EncodeIdx/timestampEof` are between 0.045 and 0.055 secs
- Inter Camera Lag : Lag between same frame of different cameras < 0.005

**Comment by deanlee** [comment]
>     * [ ]  If the camera drops a frame, a blank frame should be inserted and a flag raised
It is very difficult to do this perfectly in loggerd. and will greatly increase the complexity and performance overhead.
It may be more appropriate to do this in other places, such as framereader

**Comment by adeebshihadeh** [comment]
@nuwandavek can you expand the list above with all the checks we do offline?

**Comment by gregjhogan** [comment]
> > ```
> > * [ ]  If the camera drops a frame, a blank frame should be inserted and a flag raised
> > ```
> 
> It is very difficult to do this perfectly in loggerd. and will greatly increase the complexity and performance overhead. I think it may be more appropriate to do this in other places, such as framereader or replay

I really want blank frames to easily keep video playback in connect and cabana always in sync with the log data, but now that I think about it more it seems kind of impractical.  For example, an easy case to detect and try to compensate for is when the encoder fails to write out a frame.  But how do we insert a blank frame in?  I assume we have to shove another frame through the encoder which may fail again.  We also don't put anything into the qlog/rlog when a frame is dropped, but again I suppose that can fail, too.

**Comment by jpc** [comment]
Hi, I work at Collabora and we invest a lot of work into improving GStreamer – the real-time multimedia framework. Recently we were researching into how people are doing data sampling when uploading videos from embedded devices.

One thing we are curious about is whether it would be useful to have Open Source GStreamer components that could automate the process of: getting the camera data, accurately time-stamping it, running it through a (ONNX?) DL model, compressing it and uploading/streaming it over the internet based on the output from the model.

Since this seems to have a lot of overlap with the problems you are working on I was wondering whether we could compare notes and maybe help each other out?
