### ISSUE TITLE
1.Key chain has stopped 2. Keyboard AOSP has stopped. Tried Reflashing but get invalid syntax error please advise.

### ISSUE THREAD

**Issue by skyej944** [commaai/openpilot#22201]
This is following the solution put forward by @VirtuallyChris for these error messages. Trying to flash in fastboot mode with eon-neos. 

I'm running ubuntu on windows 10. 

Get this when trying to clone (just stays at this point):
`
skyej944@SkylersHp:~$ git clone https://github.com/commaai/eon-neos.git
Cloning into 'eon-neos'...
`
I downloaded and unzipped, located the folder location and run download.py
`
skyej944@SkylersHp:/mnt/c/users/skyler/downloads/eon-neos-master/eon-neos-master$ python download.py
already downloaded https://commadist.azureedge.net/neosupdate/recovery-f01a55c9ba52ca57668d1684c6bf4118efd31916b04f8c1fcd8495013d3677eb.img
already downloaded https://commadist.azureedge.net/neosupdate/ota-signed-5dc2575d713977666a8e14ae1b43a04d7f63123934c80fa10751d949a107653e.zip
`
Then I run flash.sh and get:
`
skyej944@SkylersHp:/mnt/c/users/skyler/downloads/eon-neos-master/eon-neos-master$ python flash.sh
  File "flash.sh", line 8
    if [ ! -f $FASTBOOT ]; then
         ^
SyntaxError: invalid syntax
`
I barely know what I'm doing so I tried:
`
  File "flash.ps1", line 2
    $fastboot = "platform-tools/fastboot.exe"
    ^
SyntaxError: invalid syntax
`

Please help!

**Comment by adeebshihadeh** [comment]
Your issue is `python flash.sh`. Run `./flash.sh` instead. I also see `flash.ps1` in your pasted outed; that script is only for windows. Stick to ubuntu for the easiest experience. 

I'm going to close this though since our issue tracker isn't for support. If you need further help, check out the community discord (https://discord.comma.ai) or support@comma.ai
