### ISSUE TITLE
Laneless almost drove into curb due to abrupt change in lighting under bridge

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#22772]
### Describe the bug

Was driving on Laneless. Very sunny outside then went under a short bridge and OP was almost about to drive into the right curb before me taking over the steering wheel. Looking at the video this is clearly an issue with Comma Two not adjusting the exposure quickly enough for lower lightning. This is on my commute and I've never had this issue occur before. Usually, the Comma Two exposure adjusts really quickly.

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

d359be01b5dd56bf|2021-11-01--14-08-45--9

### openpilot version

0.8.9

### Additional info

Incident occurred at Mon, 1 Nov @14:18:00.The incident

**Comment by pd0wm** [comment]
I went through some of your older drives, and exposure always changes quite slowly there. But in your previous drives it was not as sunny outside, and usually behind other slower moving traffic, giving exposure a bit more time to correct.

It also looks like there are no lane lines at all in the tunnel, making it pretty hard to distinguish any references in these adverse lighting conditions.

I don't think we'll be making any changes to comma two auto exposure anymore, since those changes can have many unexpected effects. Hopefully, future models encounter more of these situations in the dataset and learn to better deal with them using other queues like the end of the tunnel.
