### ISSUE TITLE
Fix lane change behavior when blinker is turned off early

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#2303]
Currently when you turn off the blinker off the lane change state goes back to off. If I understand the code correctly this turns the lane lines back on immediately. This causes inconsistent lane changes if you turn off the blinker before the lane change is complete.

**Comment by xps-genesis** [comment]
adding to this point there is no graceful way to cancel the lane change once initiated. 
order of operation to reproduce-
1.) turn on blinker
2.) nudge the steering to initiate LC
3.) Driver realizes he doesn't want to LC, so tries to nudge the wheel in the opposite direction.
OP is still trying to complete the Lane change.

expected behavior is LC should cancel on opposite nudge and should try to maintain the initial lane.

**Comment by pd0wm** [comment]
We can't really cancel a lane change. The model will continue until it thinks it's done. We can only turn the lane lines back on, but that would be a hack.
