### ISSUE TITLE
Hyundai: Cruise Set Speed increasing without driver input while engaged

### ISSUE THREAD

**Issue by KyleGreenlaw** [commaai/openpilot#23252]
### Describe the bug

Was recently driving and while engaged on the highway, Openpilot started to increase set cruise speed without my input. I disengaged and re-engaged to see if it happened again, and it did. I haven't been able to reproduce since having the bug

Restarted my comma 3 and the bug did not reoccur after restart.

2021 Hyundai Sonata Hybrid, Running Master, Comma 3

route:fe80a4e1cedec853|2021-12-15--21-34-09--10

<img width="470" alt="Screen Shot 2021-12-16 at 11 37 33 PM" src="https://user-images.githubusercontent.com/4014821/146484958-a939d7db-6af2-4f0c-91e1-784119729565.png">

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

route:fe80a4e1cedec853|2021-12-15--21-34-09--10

### openpilot version

0.8.12

**Comment by pd0wm** [comment]
Very strange. I checked the CLU11 message, which contains the button pressed state, but neither the cluster nor openpilot was sending messages to increase the set speed.

The only thing odd was just before it started happening the button state was 7, which is not one of the known button states in openpilot, so not sure what that means.

Without a good way to reproduce this might be a tricky bug. It might not even be an openpilot bug.
![2021-12-17-123719_653x708_scrot](https://user-images.githubusercontent.com/1314752/146539332-5c39f3ad-0cee-4867-8088-44072dfdbfab.png)

**Comment by pd0wm** [comment]
@gregjhogan just noticed you were using openpilot longitudinal, which I didn’t notice.

Need to look into it some more!

**Comment by KyleGreenlaw** [comment]
I’m out right now, unable to upload the last drive I’ve done. I think I’ve been able to duplicate the error. If you hold down the button that adjusts distance, and then engage open pilot the speed will begin to increase.

I’ll have to get on Wi-Fi, upload it and take a look

**Comment by KyleGreenlaw** [comment]
fe80a4e1cedec853|2021-12-28--17-40-52--19

Here’s a route of the errors. The last 5 minutes of the drive is when I start it. 

It involves holding the distance adjustment button and then engaging OP.
(Why I did this I’m not sure lol)

**Comment by sshane** [comment]
Should be fixed by https://github.com/commaai/openpilot/pull/24674, let me know if it isn't

You initially triggered this by holding the gap dist button with the accel button, then let go the gap button and the signal transitioned to accel and back to dist gap without reaching zero, so CarState never sent an unpressed event for the accel button. Then you happened to never press it for the rest of the drive, so controlsd thought the accel button was being pressed this whole time 

![Screenshot from 2022-06-11 02-28-09](https://user-images.githubusercontent.com/25857203/173182119-99cafe90-eaae-4657-8a03-8fbe4afb5c05.png)
