### ISSUE TITLE
poor GPS reception

### ISSUE THREAD

**Issue by antaod** [commaai/openpilot#23343]
### Describe the bug

I just got C3. After driving for a few minutes, an error message pop-up "poor GPS reception". It occurred every trip. I did a hard reset per recommendation from comma.ai support, but the problem continues.  

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

a96d2488318ec4b8|2021-12-31--02-15-22--0

### openpilot version

0.8.12

### Additional info

position of camera
![IMG_6559](https://user-images.githubusercontent.com/96921598/147835602-2cb717d5-07a0-4fbe-9a81-923536fc478b.jpg)
![IMG_6560](https://user-images.githubusercontent.com/96921598/147835603-ba9097cd-c500-4235-a2fc-ba2f63af9634.jpg)

**Comment by L3Fingers** [comment]
This is not something I reported. I don't believe that's my car. I haven't submitted any bug or trouble tickets for my C3. Unless its something the C3 did itself?
Thank you,John

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 31, 2021 at 12:33 PM, ***@***.***> wrote:   


Describe the bug

I just got C3. After driving for a few minutes, an error message pop-up "poor GPS reception". It occurred every trip

What hardware does this issue affect?

comma three

Provide a route where the issue occurs

a96d2488318ec4b8|2021-12-31--02-15-22--0

openpilot version

0.8.12

Additional info

position of camera

**Comment by robbederks** [comment]
I've taken a quick look at the qlogs, and it looks like there are no raw gps messages coming in, waiting for your device to come online to confirm.
Most likely the cable between your main PCB and the gps module might have come undone in shipping. If you're comfortable disassembling the device you can take a look yourself to see if both sides of the cable are fully seated, if not, please contact support@comma.ai and we'll have your device fixed in house! Sorry for the trouble!

**Comment by antaod** [comment]
Thank you for checking this for me.

Antao
