### ISSUE TITLE
Stuck on max following distance: 2021 Rav4 Hybrid

### ISSUE THREAD

**Issue by tglevrie** [commaai/openpilot#23536]
### Describe the bug

The following distance can not be adjusted, and is stuck on the max following distance. I have not been able to since I got the vehicle. It wasn't an issue with my 2020 Toyota Camry Hybrid, so I'm just making the issue known. Other than that, the unit runs great. It is a 2021 Toyota Rav4 Hybrid (XSE, if it matters). 

### What hardware does this issue affect?

comma three

### Which car does this affect?

Toyota Rav4 Hybrid 2021

### Provide a route where the issue occurs

1c05783affe6641f|2022-01-14--19-21-37

### openpilot version

0.8.12

### Additional info

Openpilot was engaged around 19:23:43 in the clip, if that helps. Although, I know this a car issue. Thank you comma team!

**Comment by vanillagorillaa** [comment]
This isn't a bug, its a different experience between the two vehicles due to vehicle specific limitations. Vehicles that openpilot controls longitudinal on (gas/brake functionality), in your case your RAV4, the following distance is not adjustable. On vehicles that openpilot is not in control of longitudinal, such as your Camry where this functionality was left to the factory control, you can change the distance.
