### ISSUE TITLE
Unit test for Toyota safety param

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#2383]

**Comment by ShaneSmiskol** [comment]
Here's my last 14 drives that had enough samples for a prediction, the current script doesn't seem very accurate. 

![Screenshot_91](https://user-images.githubusercontent.com/25857203/96826833-d1a57c80-13f9-11eb-82b3-08265cfd5434.png)

I think the varying results could be caused by random occurrences when EPS and CMD torque become out of sync, like the following examples:

![Screenshot_96](https://user-images.githubusercontent.com/25857203/96827198-9fe0e580-13fa-11eb-9154-3d44a40c792b.png)

And:

![Screenshot_97](https://user-images.githubusercontent.com/25857203/96827308-edf5e900-13fa-11eb-8663-ffd1b3cec81e.png)

**Comment by ShaneSmiskol** [comment]
If I filter the data in the script and only allow data where the difference between CMD and EPS is less than 100 it seems a bit better, could go lower with the threshold
![Screenshot_98](https://user-images.githubusercontent.com/25857203/96829745-d79e5c00-13ff-11eb-809b-7757d8c90767.png)

```
Raw data:      mean: 0.9235, std.: 0.0524
Filtered data: mean: 0.9171, std.: 0.0389
```

**Comment by ShaneSmiskol** [comment]
I think #2647 will fix these issues

**Comment by adeebshihadeh** [comment]
Appears the factor is non-linear. We need to understand it better.
