### ISSUE TITLE
Nissan Leaf - Controls Mismatch on engage

### ISSUE THREAD

**Issue by razem-io** [commaai/openpilot#23964]
### Describe the bug

Since 0.8.13 I am no longer able to engage OpenPilot as it results in a "controls mismatch" immediately when engaged. Multiple users have written about similar issues with their leafs in the OpenPilot Nissan Discord channel.

It might be related to [Immediate disables](https://blog.comma.ai/0813release/#immediate-disables) introduced in 0.8.13.

### What hardware does this issue affect?

comma three, comma two

### Which car does this affect?

Nissan Leaf 2018-2022

### Provide a route where the issue occurs

ba3e03ccb4b26329|2022-03-14--09-47-05

### openpilot version

0.8.13

**Comment by TheKirkMiller** [comment]
Another route with this issue is here: f49cbfe935911658%7C2022-03-08--06-34-19

At 230 seconds "SET" is pressed, Cruise/OP seems to try and engage until
232 seconds when the "PROPILOT_NA_MSGS" flag is set to a value of '7' which is also where OP throws the controls mismatched error, and this flag keeps a value of '7' then at
238 when "SET" is pressed again and OP gives the same controls mismatch error, until
252 seconds when OP then engages properly after the "PROPILOT_NA_MSGS" flag is set back to '0'

I believe this has something to do with the second half of the Immediate disables section of the 0.8.13 blog post, but I don't know how to further debug what values OP and panda would be disagreeing on, which causes the car to go into it's "not available" mode for 20 seconds. Because I've also had this issue on other routes that completely disabled LKAS/OP through multiple ECU codes being thrown on the dashboard.
