### ISSUE TITLE
Toyota: EPS fault while overriding

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#24943]
This is a rare steering fault while overriding. There's only one instance on 0.8.14:
```
TOYOTA RAV4 HYBRID 2017                  c6f9dea34ce475de|2022-06-05--20-30-22--8
```

**Comment by sshane** [comment]
Only qlogs available, but looks like a normal permanent fault caused by high user torque. Not sure of the exact conditions causing this, however previously I've seen cases where the requested torque was high and static for multiple seconds before the fault, but in this case the user had only just engaged.

It may be caused by applying any torque when the user steering torque is high enough, I'll check the other segments from users with permanent faults to verify.

![Screenshot from 2022-06-21 23-05-53](https://user-images.githubusercontent.com/25857203/174955355-74d85c31-e764-442a-b08b-51f8841545b3.png)

**Comment by sshane** [comment]
Was able to reproduce this pretty easily. Think the conditions for a fault are:
- `STEERING_LKA->STEER_REQUEST` is 1
- `ABS(STEER_TORQUE_SENSOR->STEER_TORQUE_DRIVER)` is greater than 500 units for more than 50 frames

See where user torque was 49-51 frames before a temp fault that lead to a perm fault:

![Screenshot from 2022-08-30 20-33-34](https://user-images.githubusercontent.com/25857203/187586922-95b99f5a-95d8-4ac3-bda9-61ade8ffd8fd.png)
![Screenshot from 2022-08-30 20-33-47](https://user-images.githubusercontent.com/25857203/187586928-f4ac2fdf-3143-4163-b509-b933c69217fa.png)
![Screenshot from 2022-08-30 20-33-40](https://user-images.githubusercontent.com/25857203/187586924-3a565078-2ddd-4ae2-823c-87cd1c2b8d41.png)
