### ISSUE TITLE
Camera frame rate too low

### ISSUE THREAD

**Issue by moshjaines** [commaai/openpilot#25025]
### Describe the bug

After boot before the orange fork warning a grey warning pops up and says camera frame rate too low reboot device, it goes away and all functions seem to work normally 

### Provide a route where the issue occurs

 ea53462ef36d4315|2022-07-02--16-21-09

### openpilot version

0.8.15

**Comment by pd0wm** [comment]
I noticed too on my own device. What's actually going on is that the first iteration of controlsd takes a very long time to run, this triggers a false positive on the camerad frequency check.

The bug started to show up when the fingerprinting time was increased from 0.25 to 1 second in https://github.com/commaai/openpilot/commit/f0062f624260bcbdadeec643c993ac597b73c4fc, but this not actually the root of the problem.

When running a non-release branch of openpilot the startup alerts prints the current git branch, which involves running `git rev-parse --abbrev-ref HEAD` in a subprocess. This happens deep inside some alert callback function: https://github.com/commaai/openpilot/blob/master/selfdrive/controls/lib/events.py#L225. Normally this is a relatively fast operation. However, after increasing the fingerprint delay by 0.75 seconds this `git` ends up later in the startup process and  suddenly takes over multiple seconds to complete.

I'm not exactly sure why git suddenly takes longer. My guess would be increased io contention due to loggerd starting, or killing `updated` when going onroad causes git to do some housekeepin on the next run.
