### ISSUE TITLE
C3 Crash Mid Drive (Again)

### ISSUE THREAD

**Issue by JamesL6** [commaai/openpilot#26451]
### Describe the bug

This is the 2nd time in the last few weeks that my C3 has crashed during mid-drive.

I opened up an issue a little over 2 weeks ago when this first happened, as you can see here: https://github.com/commaai/openpilot/issues/26214

### Provide a route where the issue occurs

76fcc86c5aa85c45|2022-11-04--21-09-42--0

### openpilot version

Master - 0.8.17

**Comment by adeebshihadeh** [comment]
Unfortunately, this isn't something that's easily fixable. It's also quite rare and only affects a few devices. You have a few options: keep it as-is and wait for a fix, re-seat the NVMe drive yourself, or send it back to us to fix it up. If you choose to reseat it yourself, I recommend also wiping the contacts on the end of the drive.

Thanks again for the report, but next time please comment in #24302 instead of opening a new issue.
