### ISSUE TITLE
micd sometimes crashes on startup

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#26935]

**Comment by MoreTore** [comment]
Are you guys able to reproduce this error reliably? I only encounter this issue sometimes after rebooting.

**Comment by adeebshihadeh** [comment]
happens when you start too quickly. easy to repro with:
```
diff --git a/launch_openpilot.sh b/launch_openpilot.sh
index 1525e1715..c6580c1a4 100755
--- a/launch_openpilot.sh
+++ b/launch_openpilot.sh
@@ -1,5 +1,10 @@
 #!/usr/bin/bash

+echo "starting micd"
+system/micd.py
+echo "all done $?"
+sleep infinity
+
 export PASSIVE="0"
 exec ./launch_chffrplus.sh
```

**Comment by MoreTore** [comment]
ok so this is probably due to the driver not being ready when sounddevice is started. https://github.com/spatialaudio/python-sounddevice/issues/125.

My quick fix is just switching to portaudio server using 'default' instead of 'sysdefault' or waiting for 'sysdefault' to become available by checking `sd.query_devices(device=None, kind=None)`.

**Comment by MoreTore** [comment]
Ok so for now I just added time.sleep(2) until you fix the issue.

**Comment by incognitojam** [comment]
@MoreTore feel free to try out the `micd-input-device` branch
