### ISSUE TITLE
2022 Chrysler Pacifica Hybrid Silent Failure to Steer

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#27223]
### Describe the bug

System was working fine on part of my drive, but on another part, vehicle was drifting out of the lane onto the shoulder, and display was showing "green border" for being engaged/enabled. Failed to take control. During this time, I attempted to disable ACC and reenable/set. Kept on failing to move the steering. After disabled for a bit of time, I tried again, and it appeared to work.

Something was wrong where the Comma 3 Silently failed to control vehicle, and no warnings were given.

4395faadf0a373f2|2023-02-05--11-33-47--55: towards the end of this segment, you can see the vehicle drifting off the road, and I had to manually keep on track.

4395faadf0a373f2|2023-02-05--11-33-47--56: I continued to "let go of the steering" to see if it would take control, but it continued to drift off the road with no input to steering.

### Which car does this affect?

2022 Chrysler Pacifica Hybrid 

### Provide a route where the issue occurs

4395faadf0a373f2|2023-02-05--11-33-47--55

### openpilot version

0.9.1 nightly

**Comment by sshane** [comment]
Looks like you hit a bug existing in master for the past two weeks or so when the panda safety limits were bumped without updating openpilot: https://github.com/commaai/panda/pull/985.

Basically, panda will start blocking steering messages due to the safety mismatch, and we don't log that your EPS is complaining about a temporary steering fault, so you wouldn't get a warning either.

I'm adding logging for temporary steering faults so that blocking messages like this in the future will now give you a warning: https://github.com/commaai/openpilot/pull/27303

Your car should also be fixed in mater, as it was removed from the tuning + rate limit blacklist, so you should not have experienced this issue since https://github.com/commaai/openpilot/pull/26934.
