### ISSUE TITLE
"waiting for GPS" until first vehicle motion

### ISSUE THREAD

**Issue by jyoung8607** [commaai/openpilot#28832]
### Describe the bug

Sometimes on startup, my device remains in GPS SEARCH / nav Waiting for GPS indefinitely, until the vehicle starts moving. Have noticed this three times now, when setting a nav-on-openpilot destination at my starting point.

In the background, it looks like I'm getting a fast GPS fix, but neither `liveLocationKalman.positionGeodetic.valid` nor `liveLocationKalman.gpsOK` flip to True until the vehicle moves.

It doesn't always happen. I think it might only be happening after deep sleep/SOM bootkick, or branch switch/update.

### Provide a route where the issue occurs

c5cbf3352b0f03bb|2023-07-06--12-50-49

### openpilot version

219590885fb7463f39bacbbf1d5274b7251d9e7f

### Additional info

<img width="1074" alt="image" src="https://github.com/commaai/openpilot/assets/46612682/f4bfb8d2-88a1-41dd-afc6-0ed91293c3ea">

**Comment by adeebshihadeh** [comment]
@nuwandavek is this expected behavior? can we do something about it?

**Comment by nuwandavek** [comment]
The check that is being triggered here is https://github.com/commaai/openpilot/blob/8d13ddb943de02a1d8f9f593896aa24ae38db34c/selfdrive/locationd/locationd.cc#L307C18-L307C18. In the `gpsLocation` message ( `qcom` gps), the `bearingAccuracydeg` was 0 and only began to change when the vehicle moved. Since the accuracy default values are 0, we wait for them to be non-zero to assume the gps is on. The final solution here seems to be to use the magnetometer for bearing (and to remove this check in locationd).
@haraschax should we patch this in the meantime?
![image](https://github.com/commaai/openpilot/assets/1649262/6bb21a41-9937-4be2-8a05-3907a6ace780)

**Comment by haraschax** [comment]
I think this is a failure of rawgpsd, it should not output 0 for bearing accuracy, I will look into fixing it.
