### ISSUE TITLE
investigate + test build time

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29319]
Keeping build time low is very important, and we have nothing that enforces this right now.
- [ ] tool to profile build time
- [ ] regression test
- [ ] make it faster?

**Comment by adeebshihadeh** [comment]
Does mold speed things up? https://github.com/rui314/mold

**Comment by MarinkoMagla** [comment]
Hi,

A few days before the issue was closed, I experimented with using the lld linker (https://github.com/llvm-mirror/lld) and optimization flags, and did see notable improvements in build time.

However, upon checking the closed issue, I couldn't spot any optimizations being implemented or any mention of build time improvements.

It might be worth revisiting this issue and discussing potential optimizations further.

Cheers!
