### ISSUE TITLE
[$100 bounty] Setup a PR review bot

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#30715]
To start, I'm thinking the bot's review just consists of checking that a template is filled out in the PR body. 
* keep PRs as drafts until the bot is done with its "review"
* also add a special `bot-review` label while a PR is in the bot review phase
* must run in GitHub Actions

Set this up on your own fork of openpilot, then make a PR here.

**Comment by amitsgh** [comment]
@adeebshihadeh, I would like to work on this. Could you provide additional details (if any) related to this?

**Comment by AbhinavGoel9** [comment]
@adeebshihadeh, I'm interested in working on this. Could you provide any additional details?

**Comment by mhardik003** [comment]
Can you assign this to me please?

Also could you please provide the template that you want to check along with it?

**Comment by bilalshaikh292** [comment]
heyy @adeebshihadeh  is the issue still open ? I would like to contribute ?

**Comment by hritikmunde** [comment]
Hey @adeebshihadeh , do you want any specific bot on this or anything that works?

**Comment by umairjavaid** [comment]
Hi @adeebshihadeh, I just looked into the two PRs that is open and thought to share the next,he first PR is using a Python script to solve the issue and the second one is using the Action compose feature which allows you to run a bash script to do the work you need.

Have you thought to use open source action tools that could simplify the issue and make it easier? I was thinking to use one of the next:

https://github.com/marketplace/actions/template-validator
https://github.com/marketplace/actions/pr-description-checker

As for the label for bot review, I think just having a label at the end would be more logical since the bot review would take just a few seconds. WHat do you think?

I think my previous colleague @a0m0rajab could help and provide more insights as well.


You can add this into the comment, in issues, and have a part of it as PR review for both of the Opened PRs.
