### ISSUE TITLE
[$100 bounty] Remove `setproctitle` dependency

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32660]
Replace `setproctitle` with our own small helper in `common/`. Just needs to work on Linux.

**Comment by markypizz** [comment]
Curious if I'm trending in the right direction. Thanks!
https://github.com/commaai/openpilot/pull/32666

**Comment by jyoung8607** [comment]
Truly replacing Linux setproctitle() requires clobbering the original argv(), which is some real sausage-making. However, @cl0cks4fe has taken a shot at #32691.

The other approaches are setting a thread title. `htop` doesn't show them because [it's configured not to](https://github.com/commaai/openpilot/pull/32667#issuecomment-2159110183). IMO we should fix the htop config, because then we'll actually start seeing see the thread names we're already setting in camerad, loggerd, and boardd. Then we can migrate setproctitle() users to setting thread titles, and dispose of the dependency that way.

**Comment by markypizz** [comment]
Agreed with the above. htop is looking at /proc/{pid}/cmdline, which can't be changed other than clobbering argv and the mess associated with it. Is the setting of the title purely for cosmetics or for some other reason?
