### ISSUE TITLE
Panic: Electronic Stability Control Active during normal openpilot use

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#32888]
### Describe the bug

Normal use of openpilot, required me to take control but worked fine after. unsure of what could've caused this. Comes from pulling new commits from master.

Exact occurrence is here: https://connect.comma.ai/9a31d18cd1a79c69/00000001--79aa41f7e0/3484/3526

https://github.com/commaai/openpilot/assets/65101411/6d46c508-af2f-4305-8788-5ca11c854e3a

### Provide a route where the issue occurs

9a31d18cd1a79c69/00000001--79aa41f7e0

### openpilot version

66e1810c0de88f4b927b7a46d12ba96304052ace

### Additional info

I was testing out @ugtthis new Display Alert Cluster when this panic occurred but judging on the diff between the fork and [commit from master](https://github.com/commaai/openpilot/commit/66e1810c0de88f4b927b7a46d12ba96304052ace), the code only updates UI. https://github.com/commaai/openpilot/compare/commaai:openpilot:66e1810c0de88f4b927b7a46d12ba96304052ace...ugtthis:openpilot:dac-ui

**Comment by jyoung8607** [comment]
The alert was added recently in #32743, as the resolution for your earlier issue #32737.

HKG ACC disengages on stability control activity, which disengages openpilot as well. Before that PR, you would have had a nearly silent disengagement, no warning to the driver beyond the usual sound. That's a bad thing, hence the warning. It may need to be added for other vehicles as well.

Closing since this is working as-designed.
