### ISSUE TITLE
Uninstall button in addition to Reboot in Failed to Build screen

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/openpilot#34300]
https://github.com/commaai/openpilot/issues/27041

![image](https://github.com/user-attachments/assets/08a709c2-bf86-4655-8934-ae9b0734f0db)

The `Reboot` button in this screen more or less never really solves the issue ever. Uninstall at least lets the user wipe and refresh their devices easily from either a working branch or maybe the branch that broke broke the updater and reinstalling it is the fastest way to get working.

Users can get into this state slightly periodically. This can also happen on master-ci but it can also very much happen in topical branches on comma openpilot. 

The alternative is telling users to perform a device reset by tapping the at boot to ask for a reset. While that may work, it's not very obvious and takes some explanation to do which in cases of mass Failed to Build, is tiresome to explain on Discord. It's also a bit physical sometimes. I think I might have even contributed to the wearing out of my first mount too much from doing this and I'm a permanent install user. 

But mostly, this issue exists because every time I see that screen, I can't help but look at that `Reboot` button and think you are one of the most useless buttons ever. There could be a much better button there or adjacent to it for Uninstall. It feels like it should be there.

**Comment by nelsonjchen** [comment]
Alternatively, it'll be neat too if instead of uninstall, it had a fetch and force reset button. That might be a separate issue or maybe this issue could be changed to that.

**Comment by adeebshihadeh** [comment]
You really just want this: https://github.com/commaai/agnos-builder/issues/156

**Comment by nelsonjchen** [comment]
Well, then this issue has a good suggestion for the first sentence of that issue. On this screen should be one of the entry points to that AGNOS settings menu at least.

**Comment by jyoung8607** [comment]
This comes up frequently as a support issue. There isn't near enough room on the mici screen to show anything useful, and the Reboot button doesn't fix the problem.

@nickorie I think this is a UX story worth thinking about. Right now if we can't build, the device is basically a soft brick. To break out of the loop, a user has to Google how to factory reset or reflash, or reach out to support, or Discord.

@adeebshihadeh I know https://github.com/commaai/agnos-builder/issues/156 is the long term direction, and I like it, but it's been on the backlog since 2023...  can we reconsider an interim fix? Just changing the button to uninstall would be fine for now.

**Comment by nickorie** [comment]
I would refer to what adeeb replied here.

Yes I agree with the complaints, this was a screen that did not get touched during the comma 4 UI build out. That being said, we're preparing a more uniform setup experience right now that should also be easy (design wise) to adapt for the agnos options and this sort of thing going forward; though there is no timeline to address this specific issue yet.

**Comment by magambi** [comment]
A humble opion from a user that was getting the failed build screen a lot while using a dev branch:
If a automatic build at boot was interrrupted, i.e. powered off, it left a lockfile. This lockfile would cause it to not build on next power up.  It was frustrating because I was 90% sure the software had not been updated.  Clearing the lockfile via SSH and rebooting solved the problem.  It seems like I got this lock condition more frequently lately, but that might be perception.

Anyway, my point is that before the user is forced to uninstall, the software should check to see if it is just a interrupted build, not bad code.

You guys do amazing work. Thank you.

**Comment by jyoung8607** [comment]
> ... If a automatic build at boot was interrrupted, i.e. powered off, it left a lockfile. This lockfile would cause it to not build on next power up.

The lockfile issue should be resolved by #37734.
