### ISSUE TITLE
0.6.6 Doesn't detect ignition in GM car

### ISSUE THREAD

**Issue by JasonJShuler** [commaai/openpilot#870]
**Describe the bug**
As of 0.6.6 OP is no longer able to detect ignition in my 2019 Bolt (this is working off a fork with Bolt support added)

**How to reproduce or log data**
Turn on the car - nothing happens

**Expected behavior**
I would expect Open Pilot to wake up and tell me to pay attention

** Device/Version information (please complete the following information):**
 - Device: EON Gold
 - Version: [e.g. 0.6.4], devel 2964213
note: fork here: https://github.com/JasonJShuler/openpilot
 - Car make/model 2019 Chevy Bolt EV

**Additional context**
It was working fine with the safety lock on 0.6.5

**Comment by rbiasini** [comment]
@JasonJShuler as I mentioned on Discord, the only thing that would make the ignition can based logic to fail is if panda bus 0 is connected to a CAN bus that only has another ECU broadcasting data and nothing acknowledging it (Panda can't since it's in NO_OUTPUT mode and can TXs are silent).

Other than that, since the Bolt is not officially supported (and your fork as quite a few changes that deviate from op), I'm closing this ticket.
